### ISSUE TITLE
Possible to power off display when inactive?

### ISSUE THREAD

**Issue by Lyndeno** [fairyglade/ly#261]
Is it possible to configure Ly to power off the displays when there is no input, re-enabling when a key or button is pressed?

**Comment by nullgemm** [comment]
For now, Ly does not configure displays itself so this is not something we can do, sorry :(

**Comment by tomasz-c** [comment]
@nullgemm

There is no need to implement screen handling to achieve this, just use the setterm tool.

It works fine for me:
`setterm --blank 1 --powerdown 2`

It will blank the screen after one minute of inactivity and turn off the monitor after two minutes.

Alternatively, maybe this could be achieved by adding this command somewhere in the ly scripts?

**Comment by hirak99** [comment]
I think ly could provide a way to execute a command on inactivity.

E.g. -

```ini
# part of /etc/ly/config.ini
inactivity_seconds = 500
inactivity_command = systemctl suspend
```

ly could then manage the inactivity checking, and displaying to the user a timeout.

As a workaround, I can run a background script to monitor if my desktop binary has not started for a stipulated time and do that. But it would be hell of a lot nicer if this was integrated with the tui so that it shows how much longer I have to login.
