### ISSUE TITLE
custom background image

### ISSUE THREAD

**Issue by plasmoduck** [fairyglade/ly#299]
Anyone know how I can use a custom background image for ly instead of the animation or standard black background?

**Comment by IlmastroStefanuzzo** [comment]
Ly is a CLI application. Unless you manage to convert your image to 16 colors and keep it decent you can't. And even if you managed to make that image, you should implement it yourself

**Comment by yobleck** [comment]
Like @IlmastroStefanuzzo  said if you want an image you have to convert it to ASCII art in the resolution of your terminal(not monitor res). It's kind of a pain in the neck but I've created some custom animations(a still image would just be an animation that never updates) for my self [here](https://github.com/yobleck/ly/blob/44ba320cd9e6dfd7b1293f1853acc4a91049b106/src/draw.c#L479).
Look for the doom/rainbow/nyan functions and their relevant _init funcs. I can try to answer any questions you might have, but it's been awhile since I made these animations and this project seems like it might be dead so I'm not really invested in it.

**Comment by plasmoduck** [comment]
Thanks for getting back to me guys. I was thinking something like the FreeBSD Beastie ASCII logo. Problem is I can only use my from FreeBSD pkg because when I try to compile the git source it doesn’t work cause some of the libs are different on FreeBSD.

**Comment by IlmastroStefanuzzo** [comment]
Btw you can use `jp2a` to turn jpg images to ASCII art. You can get a colored output with `--color` and adjust the width with `--width=[number of character]` (it will automatically change the height to maintain the ratio)

**Comment by IlmastroStefanuzzo** [comment]
A demonstration of `jp2a`
![Uploading Screenshot_2021-08-05-15-11-02-359_com.termux.jpg…]()

**Comment by IlmastroStefanuzzo** [comment]
A demonstration of `jp2a`
![Screenshot_2021-08-05-15-11-02-359_com termux](https://user-images.githubusercontent.com/71498817/128355882-b62e0452-1db6-484e-a417-665273f66333.jpg)

**Comment by JjersaR** [comment]
How can I add the ASCII image to the ly configuration?

**Comment by nullgemm** [comment]
As discussed in #324, ASCII art background images and profile pictures won't make it into Ly, sorry :(
