### ISSUE TITLE
Starting out slow

### ISSUE THREAD

**Issue by prinixos** [fairyglade/ly#305]
Before showing the ly login manager it is showing main system login manager then it takes about 5 seconds to show ly

**Comment by BrownCarter** [comment]
Mine too is very slow to startup on Wayland.

**Comment by markstos** [comment]
What you mean by the "main" system login manager. What other login manager  are you running?

**Comment by nullgemm** [comment]
Ly's systemd service file is configured with `Type=idle`, which is a hacky option systemd rascals introduced as a way to try to avoid having boot logs printed in the TTY. Because Ly is a terminal app, this issue impacts it a lot, and without `Type=idle` in its services file, boot logs *do* get printed on top of it.

As you might have guessed, the magic trick by which systemd's `Type=idle` tries to avoid this situation is to simply wait until most services were started... This means when you have a lot of services or your computer is simply slow, Ly can take a long time to start. But if you prefer starting fast instead of avoiding visual inconveniences, you can replace `Type=idle` by `Type=simple` in Ly's unit file.
