### ISSUE TITLE
Please post a maintenance status note

### ISSUE THREAD

**Issue by markstos** [fairyglade/ly#336]
"I had a job writing software, then I open sourced it. Now I have two jobs."

@nullgemm Thank you for sharing Ly. Clearing it's popular with a number of people and now pull requests and issues are piling up. You've given enough and don't need to take on the second job of dealing with all the work that open sourcing Ly has generated if you don't want to.

But you are in a unique position as the primary Github repo owner to decide what happens next. You could add more co-maintainers, like @SartoxSoftware who has already started to maintain a fork with bug fixes. Or you could enable the "Discussions" feature to at least move some of the chat out of issues.

One option is to create a free, "ly" Github organization and give some other people permission help run it. You could contribute as much or as little as you want. 

But right now Ly is stuck with no clear path forward with maintenance. Posting a note about your intentions or interest in alternate or co-maintainers would be helpful. Thanks!

**Comment by nullgemm** [comment]
Hi @markstos, first I appreciate your indulgence, so: *thank you*.

About Ly's status : I had plans to make some rather extensive changes in the UI system. That was four years ago. I was then in the process of designing a UI library (which I finally started implementing [last year](https://github.com/nullgemm/razorbeard)) based on the idea all positions and sizes would be computed in per-widget callbacks. This allows for easy GUI creation for me, non-artist, and has a special advantage: it translates very well to TUI, so it should be possible to generate TUI apps from GUI code transparently, by changing a simple define. I wanted Ly to use this system to both have a TUI version and a GUI version using the Linux frame buffer, for people who don't like startup logs polluting the TTY (which, sadly, we can't fix). I know, I know, this is overkill, but I thought it would be useful for other projects, and not just Ly.

Now obviously "we do these things not because they are easy, but because we thought they were going to be easy". And here we are, four years later, with the situation you described. I *am* going to finish this UI library and all associated projects, but it is clearly more than time to update Ly now. As you can see I'm not very active on open-source projects currently, this is because I am busy right now, and it's not going to get better before several months. So what I can do is create an organization with people interested in helping out as maintainers to at least fix the bugs. I'll have a look at this and contact potential maintainers as soon as I have some more time available.

Thank you for caring about this project.

**Comment by markstos** [comment]
Having recently setup a Github organization myself, the whole process of creating the repo and transferring the project to it should take < 10 minutes. Github will handle automatically redirecting the old URLs.

Start here to create the organization: https://github.com/organizations/plan

 Once setup, return to the project settings here ( https://github.com/nullgemm/ly/settings ) then find  "Danger Zone" and
the option to transfer the repo to the organization. 

The username `ly` is already taken so it can't be used for an org name, so the hardest part may be picking the organization name. Maybe `ly-dm`.

**Comment by nullgemm** [comment]
As some of you might have noticed, @AnErrupTion joined me as a maintainer, and some major bug fixes and PRs have already been merged. I am slightly less busy right now so I will be helping out for some time before going back to my other projects, when I feel comfortable doing so.
