### ISSUE TITLE
How to set default DM

### ISSUE THREAD

**Issue by beucismis** [fairyglade/ly#337]
Hi, I'm use Debian Unstable. I want to set default DM as ly. According to the Debian wiki just need to run `dpkg-reconfigure ly` command. But it's not working.

Error:
![ss_1644698539](https://user-images.githubusercontent.com/40023234/153727700-81d76e5a-8b02-480b-8a48-2a19e1195169.png)

I downloaded and installed the package from this [link](https://github.com/nullgemm/ly/releases/download/v0.5.0/ly_0.5.0.zip).

**Comment by markstos** [comment]
If you installed a `.zip` file, that's a `.deb` file, so you didn't install a Debian package, which is why that Debian tool doesn't work. I'm not sure which Debian repos have Ly, but once you find and set up that repo, the install command would then be `sudo apt install ly`. and _then_ you could use the `dpkg-reconfigure` command on the package.

**Comment by Zook780** [comment]
sudo systemctl enable ly and compile it from here

**Comment by beucismis** [comment]
Thanks.

**Comment by Zook780** [comment]
> Thanks.

Also chmod +x .xinitrc if you have one or else you would just logout
