### ISSUE TITLE
Make ly compatible with the s6 init system?

### ISSUE THREAD

**Issue by qazerito** [fairyglade/ly#344]
Is there a way to enable the ly service on s6, currently it is outputting "failed to access console".

**Comment by nullgemm** [comment]
I never tried s6 but it sure is an interesting project, supporting it as an init system would be amazing

**Comment by jackghg** [comment]
and dinit , openrc, runit

**Comment by anoraktrend** [comment]
Mkinit

**Comment by thinkoid** [comment]
FWIW, I am currently running ly on my Artix with s6+s6-rc, as a service. Not entirely and fully tested but it seems that the basics are there. I am using this repo, [ly-s6](https://github.com/thinkoid/ly-s6). Basically, make sure that getty is not running on tty2 (remove the file named tty2 from getty/contents.d and reload the database). Then, either bring up the service from a terminal, or touch a file named ly in the default/contents.d directory (and, obviously reload) to have it run at the next boot. Again, not fully tested, YMMV. Also, notice that the script is a bash script because I barely started to scratch the surface of execline (the tool of choice in s6 world). Also, it may be the case that making this service a longrun service is pbb not the right choice. It most likely should be a oneshot but I am not sure. HTH

**Comment by AnErrupTion** [comment]
Implemented in master, closing.
