### ISSUE TITLE
Void Linux runit 

### ISSUE THREAD

**Issue by pixthehe** [fairyglade/ly#401]
Ive installed it and tested it. After that i made the service and it was in /etc/sv/ly. Then I made a file called run with the contents of 
`
#!/bin/sh

exec /usr/bin/ly
`
I restart the computer and it just stays on the tty.
PS, yes i linked it to /var/services

**Comment by Cavernosa** [comment]
There's a fork with a runit service, some people said it worked: https://github.com/drozdowsky/ly-void/tree/master/res/ly-runit-service

Not sure if it _still_ works, though.

Correct me if i'm wrong but, i think running only exec doesn't work is because ly can't daemonize itself, so it just stays running in the background.
For OpenRC simply using getty worked, it seems to be roughly the same process for runit (as can be seen in the linked fork).
