### ISSUE TITLE
startup script?

### ISSUE THREAD

**Issue by dxcvvxd** [fairyglade/ly#422]
might be a stupid question but how do i make a startup script for ly? xinitrc?

**Comment by Cavernosa** [comment]
Confused on waht you want to do...
You mean an init script? You're gonna need to learn how to write scripts for your init, if it's not already been done.
Do you want to run custom stuff instead of the traditional DE or WM? ([CustomXSession](https://wiki.ubuntu.com/CustomXSession))

**Comment by MadcowOG** [comment]
I am going to guess what you are looking for. I see two possibilities (Stop me if I'm wrong with either).
1. You are wondering how to start up ly with xinitrc. I'm sorry, that isn't how it works. Ly is started by your init system. For most distros this is systemd, in which case follow the install instructions from the readme. Only OpenRC and SystemD are supported at the moment.
2. You are wondering how to start your Desktop Envrionment or Window Manager of choice. In which case I might be able to help you. To allow my xinitrc to start multiple WMs and DEs I used a case statement to switch between different choices based on the input arg for the xinitrc script.
This the bottom of my xinitrc:
``` Sh
# dwm function
dwmStart()
{
	# Polkit
	lxsession &

	# Compositor
	#picom -b --experimental-backends &

	# Status Bar
	slstatus &
	#dsblocks &

	# Loop dwm upon exit.
	while true; do
		dwm > /dev/null 2>&1
	done


	# Start dwm
	exec dwm
}

# bspwm function
bspwmStart()
{
	# Polkit
	lxsession &

	# Set cursor
	xsetroot -cursor_name left_ptr

	# Set background
	#hsetroot -solid "#052e70"
	hsetroot -solid "#000000"

	# Compositor
	picom -b --experimental-backends &

	# Start bspwm
	exec bspwm
}

session=${1:-"dwm"}

case $session in
	"dwm"	 		) dwmStart;;
	"bspwm"		) bspwmStart;;
	* 		 		) exec $1;;
esac
```
Then I create an .desktop file for my window manager/desktop environment in /usr/share/xsessions, ly will look here for different WMs and DEs to start. This desktop file will point to the xinitrc script and give an arg for the WM/DE you want it to start.
This is my desktop file for dwm:
``` desktop
[Desktop Entry]
Name=dwm
Comment=Dynamic window manager
Exec=/home/user/.xinitrc dwm
Type=XSession
```

If either of these are wrong, please give more information, so that we may help.

**Comment by dxcvvxd** [comment]
thanks guys, figured it out. im not very familiar with inits and stuff, sorry
