### ISSUE TITLE
segfault: `make run` fails on debian

### ISSUE THREAD

**Issue by mchaker** [fairyglade/ly#468]
just pulled the latest git repo, commit 3366248

`make` seems to succeed -- things are compiled

however `make run` results in:

```
Segmentation fault
make: *** [makefile:64: run] Error 139
```

trying to install `ly` for systemd seems to "work" (as in, it installs the files) but then results in the service just failing to start (so `ly` never actually works after being installed)

**Comment by mindsDevCom** [comment]
Introduced by 19153760d343ae9b46888806404e88033e2b628c

Changing 
`char* name_simple = strdup(name_len);`
to
`char* name_simple = strdup(name);`

in _input.c_, line _199_ fixes the issue.

**Comment by mchaker** [comment]
That worked! Thank you so much

**Comment by aksu560** [comment]
This is still happening when building on Ubuntu 20.04

**Comment by OliverIngle** [comment]
I have just tried installing the latest release (`v0.6.0`), but when I got to the `sudo make run` step I got the error mentioned above 
`Segmentation fault (core dumped)
make: *** [makefile:64: run] Error 139`
So I tried the fix mentioned above, changing the line 199 of `inputs.c`, but it seems to have already been corrected since the original issue, but yet I'm still getting the error.

I'm using Ubuntu 22.04.3 LTS with Gnome.
