### ISSUE TITLE
No output on display port on boot

### ISSUE THREAD

**Issue by ghost** [fairyglade/ly#512]
NVIDIA card, reboots and HDMI work fine

**Comment by AnErrupTion** [comment]
@veranorooz Could you be a bit more specific please? Do you mean that you have no output on a monitor connected to your NVIDIA card, but then it works fine after a reboot?

**Comment by veranorooz** [comment]
Sorry about the ambiguity. After a cold boot, I don't get display out of the display port of the NVIDIA GPU until I login. It's not a no signal situation though so monitor doesn't go to sleep but also it's just black. HDMI on the same card and SDDM works. And this doesn't reoccur on reboots, only cold boots.

**Comment by fenamori** [comment]
try manually selecting your kernel in your bootloader instead of letting it go automatically. like literally just scroll through the options and then select your default kernel. for some reason, this is completely negating this issue for me (i've been dealing with it on and off for months, I _also_ have an NVIDIA card).

**Comment by AnErrupTion** [comment]
This is probably an issue with text mode in general (at least on OP's machine) and not an Ly issue. And since OP has deleted their account, I'll close this issue.
