### ISSUE TITLE
Ly Only Taking Up Part of the Screen

### ISSUE THREAD

**Issue by VoxAndrews** [fairyglade/ly#567]
Ly only seems to take up part of the screen, notably the centre portion of it. Is there any way to set the resolution of Ly or not?

![image](https://github.com/fairyglade/ly/assets/26544407/67982fbe-f879-4f6c-adae-3a87b75d5230)

**Comment by llc0930** [comment]
I think you may need to set the resolution of grub?

**Comment by VoxAndrews** [comment]
I shall give that a go, cheers! Trying to set up a custom Ubuntu OS and theres a few things I gotta do to get it running, haha

**Comment by TheAwesome98-Real** [comment]
> Ly only seems to take up part of the screen, notably the centre portion of it. Is there any way to set the resolution of Ly or not?
> 
> ![image](https://private-user-images.githubusercontent.com/26544407/295487183-67982fbe-f879-4f6c-adae-3a87b75d5230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzE1MzcsIm5iZiI6MTcwOTIzMTIzNywicGF0aCI6Ii8yNjU0NDQwNy8yOTU0ODcxODMtNjc5ODJmYmUtZjg3OS00ZjZjLWFkYWUtM2E4N2I3NWQ1MjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE4MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2M2NlYzFhM2M4NTM0MDYwMWQzOWY1MzcyY2I1NmVmMmZjMjZkM2YzNzcyNWI2YTBmZWM3YTE5ZDg4NjNmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R0h-Bl8jOXyZOGP7c18_8ceabngo8iTH8TGROaMhWI8)

this is just the way your emulator displays lower resolutions. on a real computer this would display at the mode of the lowest-resolution connected monitor in the top-left of all monitors, and on a vm, like was mentioned previously, you need to change grub's resolution.

**Comment by AnErrupTion** [comment]
@VoxAndrews It looks like you're using VirtualBox (judging by the small bottom bar). If so, the reason Ly (and consequently, the TTY) are displaying like that is because I believe the Guest Additions don't load automatically by default on Linux. As a workaround, you can try to make them load before Ly (perhaps as a system service, if that's possible) or, as already mentionned before, change the resolution in your bootloader configuration to better suit your needs.

However, this is not an Ly issue, so I'm closing it.
