### ISSUE TITLE
Permission problems after 2nd Login

### ISSUE THREAD

**Issue by Shallrath** [fairyglade/ly#575]
When logging in after booting using Ly, everything works as expected. When logging out and back in again, I seem to have restricted permissions on my system. XFCE does not allow me to suspend/reboot/shutdown, I need to type the root password when accessing a USB drive and disabling/enabling Bluetooth does not work anymore. These problems persist until I reboot. I never encountered this with lightdm.

**Comment by Aniamon** [comment]
I have the same issue on Arch but only when i switch between window managers

**Comment by Stephixus** [comment]
Same issue on Manjaro, with i3 and hyprland.

**Comment by JosephMehdiyev** [comment]
- Log out, sleep, reboot, power off your system
- Change brightness of your screen (laptop). Mine stucks at 30%.
- Unable to write your internal HDD, USB drives. Has read permissions, though.
Unless you provide your sudo password.

To reproduce the issue, simply log out from your session and log in back. It happens occasionally, though.

I happened to find this issue when I tried to switch from Wayland session to X11 session.  Rebooting solves the issue.
I also wanted to check if logging to root session would fix the things up without rebooting, however neither X11 nor wayland could open the root session. I managed to get an error
`/usr/bin/xauth: error in locking authority file /run/user/0/lyxauth`
I honestly don't know what it really means nor if it is helpful at all.
The issue is really annoying. There is also another bug where  Ly displays error code in login screen ( already  documented in Issues section).

**Comment by Shallrath** [comment]
I don't seem to have this problem anymore with the complete rewrite of 1.0.0

**Comment by Stephixus** [comment]
I can confirm.
All is fine now.
Thanks 😀

**Comment by AnErrupTion** [comment]
@JosephMehdiyev If your issue persists, please open a new one. Thanks!
