### ISSUE TITLE
[Question] release zig 0.13.0 support

### ISSUE THREAD

**Issue by christian-heusel** [fairyglade/ly#671]
### Pre-requisites

- [X] I have looked for any other duplicate issues

### Ly version

1.0.2

### Observed behavior

Could we get 0.13.0 support into a release? I'm getting compile errors with 1.0.2:
```
==> Starting build()...
/build/ly/src/ly/build.zig:28:33: error: no field named 'path' in union 'Build.LazyPath'
/usr/lib/zig/std/Build.zig:2171:22: note: union declared here
==> ERROR: A failure occurred in build().
```

This was already reported and fixed in https://github.com/fairyglade/ly/issues/622 but AFAIU never made it to a release 🤔 

The issue now is that the patches that I backported so far don't apply cleanly anymore: 
```
==> Starting prepare()...
Auto-merging build.zig
Auto-merging build.zig.zon
CONFLICT (content): Merge conflict in build.zig.zon
Auto-merging src/config/Config.zig
Auto-merging src/main.zig
error: could not apply e4abf79... Support Zig 0.13.0 and setting default TTY at build time (#632)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: Disable this message with "git config advice.mergeConflict false"
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Build failed, check /var/lib/archbuild/extra-testing-x86_64/chris-5/build
```

### Expected behavior

Builds without issue :)

### Steps to reproduce

1. build ly on version 1.0.2
2. still observe build error

**Comment by AnErrupTion** [comment]
I specifically avoided supporting Zig 0.13.0 for v1.0.0 because of the whole can of bugs it could potentially open (v.s. only supporting 0.12.0). To be completely honest though, that's probably fine since I really doubt bugs would be introduced by that, especially now. The actual issue to me is that, even though the patch is pretty simple by itself, I feel like introducing support for a whole new Zig version in a patch release isn't very wise. Is there really no other way for Zig 0.12.0 to be used by the Arch package?

**Comment by christian-heusel** [comment]
Are these changes expected to be non-backwards-compatible? 🤔 I have no clue about zig, that's why I'm asking 😅 
Because if they are backwards compatible I don't see any issue in making a patch release for it 👍🏻 

> Is there really no other way for Zig 0.12.0 to be used by the Arch package?

Well no real good solutions are there, just to list a few:
- I could introduce a `zig12` package and depend on that, but before doing that I'd rather withhold updates to the package until it has support for the new zig version 😊 
- Manually backport the patch to apply on the 1.0.2 (and any further) releases, which sounds like work 😄 
- Manually install old dependencies into the build environment (which is what I did for now but is not a hack I want to keep up 😅 )

**Comment by AnErrupTion** [comment]
> Are these changes expected to be non-backwards-compatible? 🤔 I have no clue about zig, that's why I'm asking 😅
Because if they are backwards compatible I don't see any issue in making a patch release for it 👍🏻

They are absolutely backwards compatible, as in, you can continue building with Zig 0.12.0 if you want.

> Well no real good solutions are there

What I can do instead is commit support for it in the `v1.0.x` branch, then you can cherry-pick it while building the package. I think releasing a version with *only* this change is pretty lackluster.

**Comment by AnErrupTion** [comment]
@christian-heusel I've done what I said above and pushed commit https://github.com/fairyglade/ly/commit/fadbbf676ad88e57cecffd501b5a4d4634064688 on branch `v1.0.x` to support Zig 0.13.0. I did change the version right before to indicate `v1.0.3`, but when cherry-picking that shouldn't be an issue. I'll leave this issue open for the time being if you encounter any issues.

**Comment by christian-heusel** [comment]
Thanks!

**Comment by AnErrupTion** [comment]
Seems like Ly v1.0.2 has hit the extra repo, so I'm closing this.
